### ISSUE TITLE
store is down?

### ISSUE THREAD

**Issue by rusefillc** [maraakate/Honda_CM400T_CDI#2]
https://cm400a.nightgrease.net/

![image](https://github.com/maraakate/Honda_CM400T_CDI/assets/48498823/b7be0638-b65d-47e5-989e-1eb1e2152220)

**Comment by maraakate** [comment]
It's moved to https://www.hondamaticparts.com

I will update the repo to reflect this.  Thanks!

**Comment by maraakate** [comment]
Link fixed, thanks for reporting!
